DROP TABLE IF EXISTS users;
CREATE TABLE users (
id SERIAL PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
phone  VARCHAR(100) NOT NULL UNIQUE,
subscription_id INT UNSIGNED NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS profiles;
CREATE TABLE profiles (
user_id INT UNSIGNED NOT NULL PRIMARY KEY,
gender CHAR(1) NOT NULL,
birthday DATE,
country_id INT UNSIGNED NOT NULL,
city_id INT UNSIGNED NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS country;
CREATE TABLE country (
id SERIAL PRIMARY KEY,
country VARCHAR(130),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS city;
CREATE TABLE city (
id SERIAL PRIMARY KEY,
city VARCHAR(130),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS genre;
CREATE TABLE genre (
id SERIAL PRIMARY KEY,
genre VARCHAR(130),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS executor;
CREATE TABLE executor (
id SERIAL PRIMARY KEY,
executor VARCHAR(130),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS lang_sound;
CREATE TABLE lang_sound (
id SERIAL PRIMARY KEY,
lang_sound VARCHAR(130),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS text_sound;
CREATE TABLE text_sound (
id SERIAL PRIMARY KEY,
text_sound TEXT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS sounds;
CREATE TABLE sounds (
id SERIAL PRIMARY KEY,
name VARCHAR(255),
executor_id INT UNSIGNED NOT NULL,
text_sound_id INT UNSIGNED NOT NULL UNIQUE,
genre_id INT UNSIGNED NOT NULL,
lang_sound_id INT UNSIGNED NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS playlist;
CREATE TABLE playlist (
sound_id  INT UNSIGNED NOT NULL,
user_id  INT UNSIGNED NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS subscription;
CREATE TABLE subscription (
id SERIAL PRIMARY KEY,
sub_desc VARCHAR(130),
price FLOAT UNSIGNED,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);